# Generated by Django 4.2 on 2023-04-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, verbose_name='상품코드')),
                ('name', models.CharField(max_length=100, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='상품가격')),
                ('stock_count', models.PositiveIntegerField(verbose_name='남은수량')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품들',
                'db_table': 'item',
            },
        ),
    ]
