# Generated by Django 4.2 on 2023-06-16 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_item_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='질문 제목')),
                ('content', models.TextField(verbose_name='질문 내용')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='작성일자')),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='질문자')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '질문들',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='판매자 답변')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='작성일자')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.question', verbose_name='질문')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
    ]
