# Generated by Django 4.2 on 2023-05-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_description_item_qna'),
        ('question', '0002_qna_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qna',
            name='item',
        ),
        migrations.AddField(
            model_name='question',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='상품'),
        ),
    ]
