# Generated by Django 4.2 on 2023-05-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_remove_qna_item_question_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QNA',
            new_name='Answer',
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
    ]
