# Generated by Django 4.2 on 2023-04-24 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '회원', 'verbose_name_plural': '회원들'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
