# Generated by Django 4.2 on 2023-06-16 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0002_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('date_created', models.DateField(auto_now=True, verbose_name='최종 수정 일자')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item', verbose_name='상품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '장바구니 물건',
                'verbose_name_plural': '장바구니 물건들',
                'db_table': 'cart',
            },
        ),
    ]
